### ISSUE TITLE
Place the clock on top of the avatar

### ISSUE THREAD

**Issue by saligari** [adhec/sddm_themes#1]
First off, great theme!!

What do I have to change to place the clock above the avatar?

Thanks!

edit: I think it'd look better by default if the clock was on top. Especially in ittu_bottom. Would look less cluttered.

**Comment by adhec** [comment]
Now there are 2 versions for each theme:

[ittu](https://www.opendesktop.org/p/1303587/)

ittu: buttons on the sides, clock on the bottom
ittu_c: buttons on the sides, clock on top of the avatar

[ittu_bottom](https://www.opendesktop.org/p/1309044/)

ittu_bottom: buttons and the clock at the bottom
ittu_bottom_c: buttons on the bottom and the clock on top of the avatar

Thanks for the feedback.

**Comment by saligari** [comment]
Whaaat!! Crazy fast reply & solution!

Thank you!!!
